// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAp8W_RbQEg573fLLvFCuDfPwD_OjI0lg',
    appId: '1:1045396451595:web:6e788bc88dd568a3e7f20e',
    messagingSenderId: '1045396451595',
    projectId: 'instagram-tutorial-8837d',
    authDomain: 'instagram-tutorial-8837d.firebaseapp.com',
    storageBucket: 'instagram-tutorial-8837d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCLWlRYo428Vagujy-M7XSRrNhDPCtXnxI',
    appId: '1:1045396451595:android:d1902c11548d3722e7f20e',
    messagingSenderId: '1045396451595',
    projectId: 'instagram-tutorial-8837d',
    storageBucket: 'instagram-tutorial-8837d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAI-ZhR-2EKhfz59xqAL5BQ1DAhxChGy5w',
    appId: '1:1045396451595:ios:7a533c75d232ab0ce7f20e',
    messagingSenderId: '1045396451595',
    projectId: 'instagram-tutorial-8837d',
    storageBucket: 'instagram-tutorial-8837d.appspot.com',
    iosClientId: '1045396451595-oi13gpuv9u1slco6jhegk2thpvo05q02.apps.googleusercontent.com',
    iosBundleId: 'com.example.instagramClone',
  );
}
